// Generated by LiveScript 1.5.0
var out$ = typeof exports != 'undefined' && exports || this;
out$.defineSchema = defineSchema;
function defineSchema(name, comment, drop, cascade){
  var dodrop;
  dodrop = drop ? "ELSE EXECUTE 'DROP SCHEMA " + name + " " + (cascade ? 'CASCADE' : '') + ";\n     CREATE SCHEMA " + name + "';" : "";
  return "DO $$\nBEGIN\n\n    IF NOT EXISTS(\n        SELECT schema_name\n          FROM information_schema.schemata\n          WHERE schema_name = '" + name + "'\n      )\n    THEN\n      EXECUTE 'CREATE SCHEMA " + name + "';\n    " + dodrop + "\n    END IF;\n\nEND\n\n$$;\n\nCOMMENT ON SCHEMA " + name + " IS '" + comment + "';";
}
out$.plv8xSql = plv8xSql;
function plv8xSql(drop, cascade){
  drop == null && (drop = false);
  cascade == null && (cascade = false);
  return defineSchema('plv8x', 'Out-of-table for loading plv8 modules', drop, cascade) + "\nDO $$ BEGIN CREATE TABLE plv8x.code (\n    name text PRIMARY KEY,\n    code text,\n    load_seq int,\n    updated timestamp\n); EXCEPTION WHEN OTHERS THEN END; $$;";
}
out$.operatorsSql = operatorsSql;
function operatorsSql(){
  return 'DROP OPERATOR IF EXISTS |> (NONE, text); CREATE OPERATOR |> (\n    RIGHTARG = text,\n    PROCEDURE = plv8x.json_eval\n);\nDROP OPERATOR IF EXISTS |> (plv8x.json, text); CREATE OPERATOR |> (\n    LEFTARG = plv8x.json,\n    RIGHTARG = text,\n    COMMUTATOR = <|,\n    PROCEDURE = plv8x.json_eval\n);\nDROP OPERATOR IF EXISTS <| (text, plv8x.json); CREATE OPERATOR <| (\n    LEFTARG = text,\n    RIGHTARG = plv8x.json,\n    COMMUTATOR = |>,\n    PROCEDURE = plv8x.json_eval\n);\n\nDROP OPERATOR IF EXISTS ~> (NONE, text); CREATE OPERATOR ~> (\n    RIGHTARG = text,\n    PROCEDURE = plv8x.json_eval_ls\n);\nDROP OPERATOR IF EXISTS ~> (plv8x.json, text); CREATE OPERATOR ~> (\n    LEFTARG = plv8x.json,\n    RIGHTARG = text,\n    COMMUTATOR = <~,\n    PROCEDURE = plv8x.json_eval_ls\n);\nDROP OPERATOR IF EXISTS <~ (text, plv8x.json); CREATE OPERATOR <~ (\n    LEFTARG = text,\n    RIGHTARG = plv8x.json,\n    COMMUTATOR = ~>,\n    PROCEDURE = plv8x.json_eval_ls\n);';
}